<template>
  <keep-alive>
    <div>
      <CaresolMainCaresol/>
      <HomeMoveText/>
      <HomeAbout/>
      <HomeRoomsView/>
      <HomePremiumServices/>
      <HomeWhyChoose/>
      <HomeGallery/>
      <HomeFacilities/>
      <FooterMainFooter/>
    </div>
  </keep-alive>
</template>
